---
# tasks file for ansible-beats

# do not quote url in apt_key (causes error)
- name: "obtain Elastic GPG key"
  apt_key: 
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: "add Elastic repo config"
  apt_repository:
    repo: "{{ beats_apt_repo }}"

- name: "Update apt cache"
  apt: 
    update_cache: yes 

- name: "Install beat package"
  apt: 
    name: "{{ item }}"
  with_items: "{{ beats_beats }}"

- name: "template beat config file"
  template:
    src: "etc/{{ item }}/{{ item }}.yml.j2"
    dest: "/etc/{{ item }}/{{ item }}.yml"
    backup: yes
  register: beats_handler_notify
  notify:
    - "restart beats service"
  with_items: "{{ beats_beats }}"
  tags:
    - beats_config

- name: "start and enable beats"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ beats_beats }}"


